### ISSUE TITLE
Add file size and type to TrashItem

### ISSUE THREAD

**Issue by jackpot51** [Byron/trash-rs#94]
When visualizing the items in the trash, it is helpful to know if the item is a file or a folder, and what size it is. I looked into both Freedesktop and Windows implementations for this, and it seems to be possible in both cases. For Linux, just getting the metadata of the file or folder in the trash is enough. For Windows, the IShellItem has a GetAttributes method that returns enough information to distinguish files from folders: https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitem-getattributes. I'm sure a similar method exists for getting the size of files in the Recycle Bin.

If desired I can work on an implementation.

**Comment by Byron** [comment]
Thanks for bringing this up, a useful feature indeed!

Yes, please do feel free to work on it, thanks for offering.

There is one potential concern that came up while thinking about the matter: How many `TrashItems` are typically returned, and is it one per file in a folder when deleting recursively? To me it feels that there is no other way but to be (allow to be) lazy about returning these values or else trashing performance would be degraded. 
On Linux it should be quite straightforward to lazily obtain these values, and I'd hope on Windows that's possible too without keeping track of some handle or otherwise limited system resource.
Lastly, I'd hope this can be implemented so that there is only one expensive call when obtaining both values.
Finally, if `TrashItems` can also be directories, then `size` would be more expensive to obtain.

Anyway 😅, I am sure you have a handle on it and will assure that any implementation wouldn't degrade performance if these additional pieces of information aren't used.

**Comment by jackpot51** [comment]
I can ensure both backwards compatibility and lazy evaluation if these items.

**Comment by jackpot51** [comment]
I have a partial implementation in #95 for freedesktop platforms. Windows will take a little longer to figure out.

**Comment by jackpot51** [comment]
I implemented Windows support.
